function roi_labels = fn_atlas_roi_labels(atlas, groi, hemisphere)
%% Returns list of atlas ROI labels fitting a general ROI (groi)

MPFC_aparc_rois = {...
    'ctx-caudalanteriorcingulate',...
    'ctx-lh-caudalmiddlefrontal',...
    'ctx-lh-isthmuscingulate',...
    'ctx-lh-posteriorcingulate',...
    'ctx-lh-rostralanteriorcingulate'...
    };
INS_aparc_rois = {'ctx-lh-insula'};
LPFC_aparc_rois = {...
    'ctx-lh-paracentral',...
    'ctx-lh-parsopercularis',...
    'ctx-lh-parsorbitalis',...
    'ctx-lh-parstriangularis',...
    'ctx-lh-precentral',...
    'ctx-lh-rostralmiddlefrontal',...
    'ctx-lh-superiorfrontal',...
    'ctx-lh-frontalpole'...
    };
OFC_aparc_rois = {...
    'ctx-lh-lateralorbitofrontal',...
    'ctx-lh-medialorbitofrontal'...
    };
PAR_rois = {...
    'ctx-lh-inferiorparietal',...
    'ctx-lh-postcentral',...
    'ctx-lh-superiorparietal',...
    'ctx-lh-supramarginal'
    };
maybes = {...
    'Left-Accumbens-area',...
    'Right-Accumbens-area'}


end