function roi_labels = fn_atlas_roi_labels(atlas_name, roi, hemisphere)
%% Returns list of atlas ROI labels fitting a general ROI (groi)
% INPUTS:
%   atlas_name [str] - atlas loaded by ft_read_atlas
%   roi [str] - label of the ROI(s) that you want to translate into atlas roi labels
%   hemisphere [str] - {'right','left','both'}, which hemisphere to plot
error('never actually wrote this, depends on the eventual use case');
switch atlas_name
    case 'fs_DK'    % 'Desikan-Killiany' atlas, default from freesurfer (aparc+aseg.mgz file)
switch roi
    case 'MPFC'
        roi_labels = {...
    'ctx-caudalanteriorcingulate',...
    'ctx-lh-caudalmiddlefrontal',...
    'ctx-lh-isthmuscingulate',...
    'ctx-lh-posteriorcingulate',...
    'ctx-lh-rostralanteriorcingulate'...
    };
    case 'INS'
roi_labels = {'ctx-lh-insula'};
    case 'LPFC'
roi_labels = {...
    'ctx-lh-paracentral',...
    'ctx-lh-parsopercularis',...
    'ctx-lh-parsorbitalis',...
    'ctx-lh-parstriangularis',...
    'ctx-lh-precentral',...
    'ctx-lh-rostralmiddlefrontal',...
    'ctx-lh-superiorfrontal',...
    'ctx-lh-frontalpole'...
    };
    case 'OFC'
roi_labels = {...
    'ctx-lh-lateralorbitofrontal',...
    'ctx-lh-medialorbitofrontal'...
    };
PAR_rois = {...
    'ctx-lh-inferiorparietal',...
    'ctx-lh-postcentral',...
    'ctx-lh-superiorparietal',...
    'ctx-lh-supramarginal'
    };
maybes = {...
    'Left-Accumbens-area',...
    'Right-Accumbens-area'}
end
end

end